// Domain data for UPA 24h scheduling system

const ACTORS = [
  { id: 'paciente',      label: 'Paciente',          short: 'P',  kind: 'externo', cases: 5, desc: 'Usuário final do sistema. Realiza pré-cadastro, confirma agendamentos e recebe notificações.' },
  { id: 'recepcionista', label: 'Recepcionista',     short: 'R',  kind: 'interno', cases: 6, desc: 'Operador da recepção. Registra a entrada, valida cadastros e emite relatórios diários.' },
  { id: 'enfermeiro',    label: 'Enfermeiro',        short: 'E',  kind: 'interno', cases: 3, desc: 'Responsável pela triagem de Manchester. Registra sinais vitais e classifica risco.' },
  { id: 'medico',        label: 'Médico',            short: 'M',  kind: 'interno', cases: 5, desc: 'Realiza consulta, registra diagnóstico, solicita exames e prescreve medicamentos.' },
  { id: 'laboratorio',   label: 'Laboratório',       short: 'L',  kind: 'externo', cases: 3, desc: 'Setor externo integrado. Confirma comparecimento e registra resultados de exames.' },
  { id: 'notificacao',   label: 'Sistema Notificação', short: 'N', kind: 'sistema', cases: 2, desc: 'Sistema integrado. Dispara SMS, WhatsApp, e-mail e push pelo app.' },
];

const USE_CASES = [
  { id: 'UC01', label: 'Cadastrar paciente',       group: 'cadastro',   actors: ['paciente','recepcionista'], rfs: ['RF01','RF02','RF03'] },
  { id: 'UC02', label: 'Atualizar dados',          group: 'cadastro',   actors: ['paciente','recepcionista'], rfs: ['RF03'] },
  { id: 'UC03', label: 'Registrar entrada',        group: 'cadastro',   actors: ['recepcionista'],            rfs: ['RF04'] },
  { id: 'UC04', label: 'Realizar triagem',         group: 'triagem',    actors: ['enfermeiro'],               rfs: ['RF05','RF06'] },
  { id: 'UC05', label: 'Classificar risco',        group: 'triagem',    actors: ['enfermeiro'],               rfs: ['RF07','RF08'] },
  { id: 'UC06', label: 'Acessar histórico',        group: 'consulta',   actors: ['medico'],                   rfs: ['RF09','RF10'] },
  { id: 'UC07', label: 'Registrar consulta',       group: 'consulta',   actors: ['medico'],                   rfs: ['RF11'] },
  { id: 'UC08', label: 'Solicitar exames',         group: 'consulta',   actors: ['medico'],                   rfs: ['RF12','RF13','RF14'] },
  { id: 'UC09', label: 'Buscar horários',          group: 'agenda',     actors: ['paciente'],                 rfs: ['RF15','RF16','RF17'] },
  { id: 'UC10', label: 'Confirmar agendamento',    group: 'agenda',     actors: ['paciente'],                 rfs: ['RF18','RF19','RF20'] },
  { id: 'UC11', label: 'Gerar protocolo',          group: 'agenda',     actors: [],                           rfs: ['RF21'] },
  { id: 'UC12', label: 'Enviar notificação',       group: 'notificacao', actors: ['notificacao'],             rfs: ['RF22','RF23','RF24'] },
  { id: 'UC13', label: 'Enviar lembrete',          group: 'notificacao', actors: ['notificacao'],             rfs: ['RF25'] },
  { id: 'UC14', label: 'Confirmar comparecimento', group: 'exame',      actors: ['laboratorio'],              rfs: ['RF26','RF27'] },
  { id: 'UC15', label: 'Registrar resultado',      group: 'exame',      actors: ['laboratorio'],              rfs: ['RF28'] },
  { id: 'UC16', label: 'Atualizar prontuário',     group: 'prontuario', actors: ['medico'],                   rfs: ['RF29','RF30','RF31','RF32'] },
  { id: 'UC17', label: 'Consultar prontuário',     group: 'prontuario', actors: ['medico'],                   rfs: ['RF10'] },
  { id: 'UC18', label: 'Emitir relatórios',        group: 'cadastro',   actors: ['recepcionista'],            rfs: ['RF34'] },
  { id: 'UC19', label: 'Encerrar atendimento',     group: 'cadastro',   actors: ['recepcionista'],            rfs: ['RF33','RF35'] },
];

const GROUPS = {
  cadastro:    { label: 'Cadastro & Encerramento', color: 'teal'   },
  triagem:     { label: 'Triagem & Classificação', color: 'purple' },
  consulta:    { label: 'Consulta Médica',         color: 'amber'  },
  agenda:      { label: 'Agendamento',             color: 'blue'   },
  notificacao: { label: 'Notificações',            color: 'sun'    },
  exame:       { label: 'Exames',                  color: 'coral'  },
  prontuario:  { label: 'Prontuário',              color: 'purple' },
};

const RFS = [
  { id: 'RF01', group: 'cadastro',    title: 'Pré-cadastro online',        desc: 'O sistema deve permitir que o paciente realize pré-cadastro pelo aplicativo ou portal web informando dados pessoais e CPF.' },
  { id: 'RF02', group: 'cadastro',    title: 'Verificação de cadastro',    desc: 'O sistema deve verificar a existência de cadastro prévio por CPF ao registrar entrada.' },
  { id: 'RF03', group: 'cadastro',    title: 'Atualização de dados',       desc: 'O sistema deve permitir atualização de telefone, endereço e informações de saúde a qualquer momento.' },
  { id: 'RF04', group: 'cadastro',    title: 'Registro de entrada',        desc: 'A recepção deve registrar a entrada do paciente vinculada a um número de atendimento único.' },
  { id: 'RF05', group: 'triagem',     title: 'Registro de sinais vitais',  desc: 'A triagem deve registrar temperatura, pressão arterial, frequência cardíaca e saturação.' },
  { id: 'RF06', group: 'triagem',     title: 'Coleta de sintomas',         desc: 'A triagem deve capturar queixa principal e sintomas associados em campo estruturado.' },
  { id: 'RF07', group: 'triagem',     title: 'Classificação de risco',     desc: 'O sistema deve aplicar Protocolo de Manchester e sugerir cor (vermelho, laranja, amarelo, verde, azul).' },
  { id: 'RF08', group: 'triagem',     title: 'Encaminhamento prioritário', desc: 'O sistema deve reordenar a fila considerando a classificação de risco em tempo real.' },
  { id: 'RF09', group: 'consulta',    title: 'Acesso ao histórico',        desc: 'O médico deve visualizar consultas anteriores, alergias e medicamentos em uso.' },
  { id: 'RF10', group: 'prontuario',  title: 'Consulta de prontuário',     desc: 'O sistema deve exibir prontuário eletrônico do paciente em até 2 segundos.' },
  { id: 'RF11', group: 'consulta',    title: 'Registro de consulta',       desc: 'O médico deve registrar diagnóstico (CID-10), conduta, prescrição e observações.' },
  { id: 'RF12', group: 'consulta',    title: 'Solicitação de exames',      desc: 'O médico deve selecionar exames de uma lista padronizada (laboratoriais e de imagem).' },
  { id: 'RF13', group: 'consulta',    title: 'Definição de prioridade',    desc: 'A solicitação deve indicar urgência (rotina, prioritário, urgente) e justificativa.' },
  { id: 'RF14', group: 'consulta',    title: 'Solicitação de retorno',     desc: 'O médico deve agendar retorno com prazo sugerido em dias.' },
  { id: 'RF15', group: 'agenda',      title: 'Busca de horários',          desc: 'O sistema deve buscar horários disponíveis considerando especialidade, unidade e prioridade.' },
  { id: 'RF16', group: 'agenda',      title: 'Filtro por unidade',         desc: 'O paciente deve filtrar horários por unidade de saúde mais próxima.' },
  { id: 'RF17', group: 'agenda',      title: 'Sugestão automática',        desc: 'O sistema deve sugerir o melhor horário com base em prioridade e proximidade.' },
  { id: 'RF18', group: 'agenda',      title: 'Exibição de opções',         desc: 'O sistema deve apresentar até 5 opções de data/hora ao paciente.' },
  { id: 'RF19', group: 'agenda',      title: 'Confirmação do paciente',    desc: 'O paciente deve confirmar agendamento via app, SMS ou portal.' },
  { id: 'RF20', group: 'agenda',      title: 'Atualização da agenda',      desc: 'O sistema deve atualizar a agenda do laboratório/especialidade em tempo real.' },
  { id: 'RF21', group: 'agenda',      title: 'Geração de protocolo',       desc: 'O sistema deve gerar protocolo único (alfanumérico, 8 dígitos) para cada agendamento.' },
  { id: 'RF22', group: 'notificacao', title: 'Disparo automático',         desc: 'Toda confirmação deve disparar notificação imediata ao paciente.' },
  { id: 'RF23', group: 'notificacao', title: 'Canais múltiplos',           desc: 'Notificações devem suportar SMS, WhatsApp, push do app e e-mail.' },
  { id: 'RF24', group: 'notificacao', title: 'Conteúdo personalizado',     desc: 'Mensagem deve incluir nome, data/hora, local, tipo de atendimento e instruções de preparo.' },
  { id: 'RF25', group: 'notificacao', title: 'Lembrete prévio',            desc: 'O sistema deve enviar lembrete 24h e 2h antes do horário agendado.' },
  { id: 'RF26', group: 'exame',       title: 'Confirmação de presença',    desc: 'O laboratório deve confirmar comparecimento via leitor de QR Code do protocolo.' },
  { id: 'RF27', group: 'exame',       title: 'Registro de faltas',         desc: 'O sistema deve marcar como falta se o paciente não comparecer em 30 min.' },
  { id: 'RF28', group: 'exame',       title: 'Resultado de exame',         desc: 'O laboratório deve anexar PDF do resultado, vinculado automaticamente ao prontuário.' },
  { id: 'RF29', group: 'prontuario',  title: 'Atualização incremental',    desc: 'Cada atendimento deve incrementar o histórico do prontuário sem sobrescrever.' },
  { id: 'RF30', group: 'prontuario',  title: 'Linha do tempo',             desc: 'O prontuário deve apresentar histórico em linha do tempo cronológica.' },
  { id: 'RF31', group: 'prontuario',  title: 'Anexo de mídia',             desc: 'O sistema deve permitir anexar imagens, PDFs e laudos por consulta.' },
  { id: 'RF32', group: 'prontuario',  title: 'Auditoria de acesso',        desc: 'Toda leitura do prontuário deve ser registrada com usuário, data/hora e motivo.' },
  { id: 'RF33', group: 'cadastro',    title: 'Encerramento de atendimento', desc: 'A recepção deve encerrar o atendimento ao final de cada caso, com motivo.' },
  { id: 'RF34', group: 'cadastro',    title: 'Relatório operacional',      desc: 'O sistema deve emitir relatório diário de atendimentos, classificações e tempo médio.' },
  { id: 'RF35', group: 'cadastro',    title: 'Indicadores de gestão',      desc: 'O sistema deve calcular indicadores: tempo de espera, taxa de no-show, taxa de retorno.' },
];

const RNFS = [
  { id: 'RNF01', cat: 'Desempenho',    title: 'Tempo de resposta',       desc: 'Operações de consulta devem responder em até 2 segundos sob carga normal.' },
  { id: 'RNF02', cat: 'Desempenho',    title: 'Concorrência',            desc: 'Suportar 200 usuários simultâneos sem degradação.' },
  { id: 'RNF03', cat: 'Disponibilidade', title: 'Uptime 24/7',           desc: 'Disponibilidade mínima de 99,5% mensal.' },
  { id: 'RNF04', cat: 'Disponibilidade', title: 'Modo offline',          desc: 'Recepção e triagem devem operar em modo offline limitado, com sincronização posterior.' },
  { id: 'RNF05', cat: 'Segurança',     title: 'Autenticação forte',      desc: 'Login com usuário, senha e 2º fator para profissionais.' },
  { id: 'RNF06', cat: 'Segurança',     title: 'Criptografia em trânsito', desc: 'Todas as comunicações via TLS 1.3.' },
  { id: 'RNF07', cat: 'Segurança',     title: 'Criptografia em repouso', desc: 'Dados sensíveis criptografados no banco (AES-256).' },
  { id: 'RNF08', cat: 'LGPD',          title: 'Consentimento',           desc: 'Coletar consentimento explícito do paciente conforme LGPD.' },
  { id: 'RNF09', cat: 'LGPD',          title: 'Direito ao esquecimento', desc: 'Permitir solicitação de exclusão de dados pessoais.' },
  { id: 'RNF10', cat: 'Usabilidade',   title: 'Acessibilidade',          desc: 'Conformidade com WCAG 2.1 nível AA.' },
  { id: 'RNF11', cat: 'Usabilidade',   title: 'Idiomas',                 desc: 'Interface em PT-BR; estrutura preparada para internacionalização.' },
  { id: 'RNF12', cat: 'Usabilidade',   title: 'Treinamento mínimo',      desc: 'Profissional deve operar o sistema com até 4h de treinamento.' },
  { id: 'RNF13', cat: 'Manutenibilidade', title: 'Arquitetura modular',  desc: 'Sistema deve ser organizado em módulos independentes (cadastro, triagem, agenda).' },
  { id: 'RNF14', cat: 'Manutenibilidade', title: 'Logs estruturados',    desc: 'Logs em formato JSON, com correlação de requisição.' },
  { id: 'RNF15', cat: 'Compatibilidade', title: 'Navegadores',           desc: 'Suporte aos 2 últimos releases de Chrome, Edge, Firefox e Safari.' },
  { id: 'RNF16', cat: 'Compatibilidade', title: 'App mobile',            desc: 'Aplicativo nativo iOS 15+ e Android 10+.' },
  { id: 'RNF17', cat: 'Integração',    title: 'API REST',                desc: 'Expor API REST documentada (OpenAPI 3.0) para integrações.' },
  { id: 'RNF18', cat: 'Integração',    title: 'HL7/FHIR',                desc: 'Suporte ao padrão HL7 FHIR R4 para troca com outros sistemas de saúde.' },
  { id: 'RNF19', cat: 'Armazenamento', title: 'Banco PostgreSQL',        desc: 'Banco de dados primário em PostgreSQL 14+.' },
  { id: 'RNF20', cat: 'Armazenamento', title: 'Backup diário',           desc: 'Backup automatizado diário com retenção de 90 dias.' },
  { id: 'RNF21', cat: 'Auditoria',     title: 'Trilha de auditoria',     desc: 'Registro imutável de todas as alterações em dados clínicos.' },
  { id: 'RNF22', cat: 'Conformidade',  title: 'CFM 1.821/2007',          desc: 'Aderência às normas do Conselho Federal de Medicina sobre prontuário eletrônico.' },
];

const CLASSES = [
  {
    id: 'Paciente', stereotype: 'entity', x: 0, y: 0,
    attrs: ['- id: UUID', '- nome: String', '- cpf: String', '- nascimento: Date', '- telefone: String', '- endereço: String', '- alergias: String'],
    methods: ['+ cadastrar()', '+ atualizar()', '+ verificarCadastro(): Boolean'],
  },
  {
    id: 'Triagem', stereotype: 'entity', x: 1, y: 0,
    attrs: ['- id: UUID', '- temperatura: Float', '- pressao: String', '- freqCardiaca: Int', '- sintomas: String', '- nivelRisco: Enum'],
    methods: ['+ registrar()', '+ classificarRisco(): Enum', '+ encaminhar()'],
  },
  {
    id: 'Consulta', stereotype: 'entity', x: 2, y: 0,
    attrs: ['- id: UUID', '- data: DateTime', '- diagnostico: String', '- prescricao: String', '- observacoes: String'],
    methods: ['+ registrar()', '+ acessarHistorico()'],
  },
  {
    id: 'ProntuarioEletronico', stereotype: 'entity', x: 3, y: 0,
    attrs: ['- id: UUID', '- historico: List<Evento>', '- medicamentos: String', '- observacoes: String'],
    methods: ['+ atualizar()', '+ consultar()', '+ anexar(file)'],
  },
  {
    id: 'Agendamento', stereotype: 'entity', x: 1, y: 1,
    attrs: ['- id: UUID', '- tipo: String', '- especialidade: String', '- prioridade: Enum', '- dataSugerida: DateTime', '- protocolo: String'],
    methods: ['+ buscarHorarios(): List', '+ confirmar()', '+ gerarProtocolo(): String'],
  },
  {
    id: 'Exame', stereotype: 'entity', x: 2, y: 1,
    attrs: ['- id: UUID', '- tipo: String', '- dataRealizacao: DateTime', '- resultado: PDF'],
    methods: ['+ confirmarComparecimento()', '+ registrarResultado()'],
  },
  {
    id: 'Notificacao', stereotype: 'entity', x: 3, y: 1,
    attrs: ['- id: UUID', '- canal: Enum', '- dataHora: DateTime', '- mensagem: String'],
    methods: ['+ enviar()', '+ agendarLembrete()'],
  },
  {
    id: 'Profissional', stereotype: 'abstract', x: 0, y: 2,
    attrs: ['- id: UUID', '- nome: String', '- login: String', '- senha: Hash', '- nivelAcesso: Enum'],
    methods: ['+ autenticar(): Boolean'],
  },
  {
    id: 'Medico', stereotype: 'entity', x: 1, y: 2,
    attrs: ['- crm: String', '- especialidade: String'],
    methods: ['+ solicitarExame()'],
  },
  {
    id: 'Enfermeiro', stereotype: 'entity', x: 2, y: 2,
    attrs: ['- coren: String'],
    methods: [],
  },
  {
    id: 'Recepcionista', stereotype: 'entity', x: 3, y: 2,
    attrs: ['- setor: String'],
    methods: [],
  },
];

const CLASS_RELATIONS = [
  { from: 'Medico',        to: 'Profissional', kind: 'inheritance' },
  { from: 'Enfermeiro',    to: 'Profissional', kind: 'inheritance' },
  { from: 'Recepcionista', to: 'Profissional', kind: 'inheritance' },
  { from: 'Paciente',     to: 'Triagem',       kind: 'assoc', label: 'realiza',       multA: '1', multB: '0..*' },
  { from: 'Triagem',      to: 'Consulta',      kind: 'assoc', label: 'gera',          multA: '1', multB: '1' },
  { from: 'Consulta',     to: 'Agendamento',   kind: 'assoc', label: 'solicita',      multA: '1', multB: '0..*' },
  { from: 'Agendamento',  to: 'Exame',         kind: 'assoc', label: 'referencia',    multA: '1', multB: '1' },
  { from: 'Agendamento',  to: 'Notificacao',   kind: 'assoc', label: 'dispara',       multA: '1', multB: '1..*' },
  { from: 'Paciente',     to: 'ProntuarioEletronico', kind: 'composition', label: 'possui', multA: '1', multB: '1' },
  { from: 'Consulta',     to: 'ProntuarioEletronico', kind: 'assoc', label: 'registrada em', multA: '0..*', multB: '1' },
  { from: 'Medico',       to: 'Consulta',      kind: 'assoc', label: 'realiza',       multA: '1', multB: '0..*' },
  { from: 'Enfermeiro',   to: 'Triagem',       kind: 'assoc', label: 'realiza',       multA: '1', multB: '0..*' },
];

const ACTIVITIES = [
  { id: 'start',  kind: 'start',    label: 'Paciente chega à UPA' },
  { id: 'a1',     kind: 'action',   label: 'Registrar entrada', rf: 'RF04' },
  { id: 'd1',     kind: 'decision', label: 'Possui cadastro?' },
  { id: 'a2',     kind: 'action',   label: 'Cadastrar paciente', rf: 'RF01' },
  { id: 'a3',     kind: 'action',   label: 'Atualizar dados',    rf: 'RF03' },
  { id: 'a4',     kind: 'action',   label: 'Triagem & sinais vitais', rf: 'RF05–RF06' },
  { id: 'a5',     kind: 'action',   label: 'Classificar risco',  rf: 'RF07' },
  { id: 'd2',     kind: 'decision', label: 'Nível de urgência?' },
  { id: 'a6',     kind: 'action',   label: 'Atendimento prioritário', urgent: true },
  { id: 'a7',     kind: 'action',   label: 'Consulta médica',    rf: 'RF09–RF11' },
  { id: 'd3',     kind: 'decision', label: 'Exames ou retorno?' },
  { id: 'a8',     kind: 'action',   label: 'Solicitar exame/retorno', rf: 'RF12–RF14' },
  { id: 'a9',     kind: 'action',   label: 'Buscar horários',    rf: 'RF15–RF17' },
  { id: 'a10',    kind: 'action',   label: 'Confirmar agendamento', rf: 'RF18–RF20' },
  { id: 'a11',    kind: 'action',   label: 'Gerar protocolo',    rf: 'RF21' },
  { id: 'a12',    kind: 'action',   label: 'Notificar paciente', rf: 'RF22–RF25' },
  { id: 'a13',    kind: 'action',   label: 'Realizar exame',     rf: 'RF26–RF28' },
  { id: 'a14',    kind: 'action',   label: 'Atualizar prontuário', rf: 'RF29–RF32' },
  { id: 'a15',    kind: 'action',   label: 'Encerrar atendimento', rf: 'RF33–RF35' },
  { id: 'end',    kind: 'end',      label: 'Fim' },
];

const SEQUENCE = [
  { from: 'P', to: 'R', label: 'chega à UPA' },
  { from: 'R', to: 'S', label: 'registrarEntrada()', rf: 'RF04' },
  { from: 'S', to: 'DB', label: 'verificarCadastro(cpf)', rf: 'RF02' },
  { from: 'DB', to: 'S', label: 'status', kind: 'return' },
  { from: 'R', to: 'S', label: 'cadastrarPaciente()', rf: 'RF01', alt: 'sem cadastro' },
  { from: 'S', to: 'DB', label: 'salvar', alt: 'sem cadastro' },
  { from: 'R', to: 'E', label: 'encaminhar p/ triagem' },
  { from: 'E', to: 'S', label: 'registrarSinaisVitais()', rf: 'RF05–RF06' },
  { from: 'S', to: 'S', label: 'classificarRisco()', rf: 'RF07' },
  { from: 'S', to: 'DB', label: 'salvar triagem' },
  { from: 'E', to: 'M', label: 'encaminhar consulta', rf: 'RF08' },
  { from: 'M', to: 'S', label: 'acessarHistorico()', rf: 'RF09–RF10' },
  { from: 'S', to: 'DB', label: 'buscarProntuario(id)' },
  { from: 'DB', to: 'M', label: 'prontuário', kind: 'return' },
  { from: 'M', to: 'S', label: 'registrarConsulta()', rf: 'RF11' },
  { from: 'M', to: 'S', label: 'solicitarExame()', rf: 'RF12' },
  { from: 'S', to: 'S', label: 'buscarHorarios()', rf: 'RF15–RF17' },
  { from: 'S', to: 'P', label: 'exibirOpcões()', kind: 'return', rf: 'RF18' },
  { from: 'P', to: 'S', label: 'confirmar()', rf: 'RF19' },
  { from: 'S', to: 'DB', label: 'atualizarAgenda()', rf: 'RF20' },
  { from: 'S', to: 'S', label: 'gerarProtocolo()', rf: 'RF21' },
  { from: 'S', to: 'N', label: 'dispararNotificação()', rf: 'RF22' },
  { from: 'N', to: 'P', label: 'SMS / WhatsApp / e-mail', kind: 'return', rf: 'RF23–RF24' },
  { from: 'P', to: 'S', label: 'comparece ao exame' },
  { from: 'S', to: 'DB', label: 'registrarComparecimento()', rf: 'RF26' },
  { from: 'S', to: 'DB', label: 'salvarResultado()', rf: 'RF28' },
  { from: 'S', to: 'DB', label: 'atualizarProntuario()', rf: 'RF29–RF32' },
  { from: 'S', to: 'R', label: 'encerrarAtendimento()', rf: 'RF33–RF35' },
];

const SEQ_LANES = [
  { id: 'P',  label: 'Paciente',       kind: 'actor' },
  { id: 'R',  label: 'Recepcionista',  kind: 'actor' },
  { id: 'E',  label: 'Enfermeiro',     kind: 'actor' },
  { id: 'M',  label: 'Médico',         kind: 'actor' },
  { id: 'S',  label: 'Sistema',        kind: 'object' },
  { id: 'DB', label: 'BD PostgreSQL',  kind: 'object' },
  { id: 'N',  label: 'Notificação',    kind: 'object' },
];

window.UPA = { ACTORS, USE_CASES, GROUPS, RFS, RNFS, CLASSES, CLASS_RELATIONS, ACTIVITIES, SEQUENCE, SEQ_LANES };
